### ISSUE TITLE
Can't compile on CentOS ~ const envVars = {...process.env}

### ISSUE THREAD

**Issue by dny238** [aliahmadcse/linktree-clone#1]
I can't compile this. It doesn't like the ... is my environment wrong somehow? 

> @ development /usr/share/nginx/html/grabsubs
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/usr/share/nginx/html/grabsubs/node_modules/cross-env/src/index.js:87
  const envVars = {...process.env}
                   ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/nginx/html/grabsubs/node_modules/cross-env/src/bin/cross-env.js:3:18)

**Comment by aliahmadcse** [comment]
I tried compiling this project in Linux Environment (Ubuntu) to see why are you facing this issue. It compiled fine for me.

Can you try using some other version of cross-env? See if that's work.
